image_width: 640
image_height: 480
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [848.47319,   0.     , 287.09502,
           0.     , 844.77828, 276.38383,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.473010, -0.570261, 0.015615, -0.031853, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [903.50449,   0.     , 278.31248,   0.     ,
           0.     , 911.62347, 278.91107,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
